### ISSUE TITLE
jko_api v0.2.6 release does not work with Rails 5.1.0

### ISSUE THREAD

**Issue by shirshendu** [jwoertink/jko_api#6]
jko_api v0.2.6 bundles perfectly with Rails 5.1.0.

However, it causes rails to crash when starting up, with the following error:
```sh
.../vendor/bundle/ruby/2.3.0/gems/jko_api-0.2.6/lib/jko_api/class_descendants_builder.rb:37:in `namespace': undefined method `qualified_const_set' for Module:Class (NoMethodError)
	from .../vendor/bundle/ruby/2.3.0/gems/jko_api-0.2.6/lib/jko_api/class_descendants_builder.rb:28:in `build_descendant'
	from .../vendor/bundle/ruby/2.3.0/gems/jko_api-0.2.6/lib/jko_api/class_descendants_builder.rb:20:in `block in build'
	from .../vendor/bundle/ruby/2.3.0/gems/jko_api-0.2.6/lib/jko_api/class_descendants_builder.rb:18:in `upto'
	from .../vendor/bundle/ruby/2.3.0/gems/jko_api-0.2.6/lib/jko_api/class_descendants_builder.rb:18:in `build'
...
```
On the master branch, I get the following error:
```sh
/vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-ec685079cd3a/lib/jko_api/class_descendants_builder.rb:37:in `const_set': wrong constant name Api::V2 (NameError)
	from .../vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-ec685079cd3a/lib/jko_api/class_descendants_builder.rb:37:in `namespace'
	from .../vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-ec685079cd3a/lib/jko_api/class_descendants_builder.rb:28:in `build_descendant'
	from .../vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-ec685079cd3a/lib/jko_api/class_descendants_builder.rb:20:in `block in build'
	from .../vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-ec685079cd3a/lib/jko_api/class_descendants_builder.rb:18:in `upto'
	from .../vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-ec685079cd3a/lib/jko_api/class_descendants_builder.rb:18:in `build'
```

**Comment by jwoertink** [comment]
Hey, thanks for reporting! 

@Justin-Mitchell Have you run in to this error?

**Comment by jwoertink** [comment]
@shirshendu When you get a chance, can you pull from https://github.com/jwoertink/jko_api/tree/rails_51 and see if this works for you? If it does, then I'll release a new version and push it up. Thanks!

**Comment by shirshendu** [comment]
Thanks for pointing me towards the correct branch. It is not failing with an exception anymore. I'm still getting `already initialized constant` warnings like the following
```
.../vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-d7bbc2256a00/lib/jko_api/class_descendants_builder.rb:71: warning: already initialized constant Api::V2
.../vendor/bundle/ruby/2.3.0/bundler/gems/jko_api-d7bbc2256a00/lib/jko_api/class_descendants_builder.rb:71: warning: previous definition of V2 was here
```
This is happening because I'm defining my custom controllers like this:
```ruby
class Api::V1::ApplicationController < ApiApplicationController
  protect_from_forgery with: :exception
end
```
Seems like the warnings are originating from the same place, but a workaround might be possible.

**Comment by jwoertink** [comment]
Ok, cool. At least the app doesn't tank, but you'll probably end up with some weird side effects. I'll keep working this out. Thanks for testing that for me!
